### ISSUE TITLE
iaaft with NaN

### ISSUE THREAD

**Issue by felixcremer** [kahaaga/TimeseriesSurrogates.jl#10]
If I use iaaft with a NaN in my time series the result is the sorted original time series. 
MWE:
```julia
ts = rand(100)
ts[1] = NaN
iaaft(ts) 
```
Is this expected behaviour?

**Comment by felixcremer** [comment]
Thanks for your explanation. 
I prepared a PR, but this is still missing tests, I hope to add them till the end of the week.

**Comment by kahaaga** [comment]
Superb, thanks! Just leave a comment when tests are added, and I'll merge the PR.
